// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaBuildDatabaseUrl =
  process.env.DATABASE_URL_ONLINE?.trim() ||
  process.env.DATABASE_URL_LOCAL?.trim() ||
  process.env.DATABASE_URL?.trim() ||
  "mysql://placeholder:placeholder@localhost:3306/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaBuildDatabaseUrl,
  },
});
